name: Unreal Engine 5 CI/CD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Environment Variables
      run: |
        # Set up environment variables for Unreal Engine
        $Env:UE4Path = "C:\Program Files\Epic Games\UE_5.0"
        $Env:ProjectPath = "${{ github.workspace }}\YourProject\YourProject.uproject"

    - name: Build Project
      run: ././CICD/build.ps1
      shell: pwsh

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: ${{ github.workspace }}\YourProject\Binaries\Win64
